
const unsigned char faile_CSS_1[] =

".head {"
"border-bottom:#fff 10px solid;"
"padding-bottom:100px;"
"margin: 0px 0px 0px 6px;"
"padding-left:0px;"
"width:100%;"
"padding-right:5px;"
"background-color: #E6E6FA;"
"height :50px;"
"clear:both;"
"border-top:#fff 100pf solid;"
"padding-top:0px;"
"font-size: 40px;"
"font-weight: bolder;"
"text-align: center;"	
"color:red;"

"}"

"#content{"
 "overflow:hidden;"
 
"}"

".link_msg {"
  "border-bottom:#fff 10px solid;"
  "padding-bottom:5px;"
  "width:15%;"
  "margin: 0px 0px 0px 6px;"
  "padding-bottom:3000px;" 
  "margin-bottom:-3000px;" 
  "background-color:#C0C0C0;"
  "padding-left:0px;"
  "float:left;"
  "height :500px;"
 "}"
 ".user_msg {"
 " padding-left:0px;"
 " border-bottom:#fff 10px solid;"
 " padding-bottom:5px;"
 "width:15%;"
    
 " margin: 0px 0px 0px 6px;"
 " margin-bottom:-3000px;" 
 " padding-bottom:3000px;"
 " background-color:#C0C0C0;"
 " float:right;" 
 " height :500px;"

 "}"

 ".txt{"
  "border-bottom:#fff 20px solid;"
  "padding-bottom:10px;"
  "width:70%;"
  "margin:0 15% 0 15%;"
 
  "height :600px;"
 	
 "}"
 ".addmsg{"
  "border-bottom:0;"
  "padding-bottom:120px;"
  "margin: 0px 0px 0px 6px;"
  "padding-left:0px;"
  "width:100%;"
  "padding-right:5px;"
  "background-color: #E6E6FA;"
  "height :60px;"
  "clear:both;"
  "border-top:#fff 100pf solid;"
  "padding-top:0px;"
  "font-size: 13px;"
  "font-weight: bolder;"
  "text-align: center;"	

 "}"
"h3.dengru"
"{"
 "text-align:center;"
 "font-size: 30px;"
"}"
"h3.denglubt"
"{"
 "text-align:left;"
 "font-size: 25px;"
"}"
"h1.alarm{"
"text-align:center;"
"font-size: 30px;"
"color:red;"
"font-weight: bolder;"
"}"
"h1.dabiaoti{"
"font-size: 40px;"
"font-weight: bolder;"
"text-align: center;"
"}"	
"h1.text_bt{"
"font-size: 30px;"
"font-weight: bolder;"
"text-align: center;"
"}"
"h1#daohang{"
"margin-top:7px;"
"margin-bottom:0px;"
"font-size:1.1em;"
"font-weight:normal;"
"padding-left:31px;"
"}"
"h1#txt{"
"margin-top:9px;"
"margin-bottom:2px;"
"font-size:1.0em;"
"font-weight:normal;"
"padding-left:31px;"
"}"
"h2{"
"margin-top:20px;"
"margin-bottom:1px;"
"font-size:0.9em;"
"font-weight:normal;"
"}"
"h3{"
"margin-top:10px;"
"margin-bottom:1px;"
"font-size:0.9em;"
"font-weight:normal;"
"text-align: right;"
"}"
"h4{"
"margin-top:1px;"
"margin-bottom:1px;"
"font-size:0.3em;"
"font-weight:normal;"
"}"
"h5{"
"margin-top:1px;"
"margin-bottom:0px;"
"color:#575757;"
"font-size:0.9em;"
"font-weight:normal;"
"}"
"h1#lianjie{"
"font-size: 18px;"
"text-align: left;"
"}";
const unsigned char faile_CSS_2[100];
const unsigned char faile_CSS_3[100];
