//网页已经确定不要轻易修改
const unsigned char user_main[] =
"<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//ENhttp://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">	"
"<html xmlns=\"http://www.w3.org/1999/xhtml\"> <head><title>光一科技股份有限公司</title> "
"<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\" />	"
"<style type=\"text/css\"><!-- "
".head {border-bottom:#fff 10px solid;padding-bottom:30px;margin: 0px 0px 0px 5%;padding-left:0px;width:90%;"
"padding-right:10px;background-color: #999999;height :80px;clear:both;border-top:#fff 100pf solid;padding-top:0px;"
"font-size: 40px;font-weight: normal;text-align: center;color:red;}"
"#content{overflow:hidden;margin: 0 0 0 5%;width: 91.6%;border-top: #fff 10px ;height :530px;background-color: #FFFFFF;}"
".link_msg {width:15%;margin: 0px 0px 0px 0;background-color:#CCCCCC;"
"padding-left:0px;float:left;height :520px;}"
".txt{border-bottom:#fff 10px solid;padding-bottom:250px;width:84%;height :500px;margin-lift:15%;"
"margin-bottom: -250px;}"
".addmsg{border-bottom:0;padding-bottom:15px;margin: 0px 0px 0px 5%;padding-left:0px;width:90%;padding-right:5px;"
"background-color: #999999;;height :80px;clear:both;border-top:#fff 100pf solid;padding-top:0px;font-size: 13px;"
"font-weight: bolder;text-align: center;}"
"h3.dengru{text-align:center;font-size: 30px;}"
"h3.denglubt{text-align:right;font-size: 23px;;color=:#FF9966;margin-top:5px;margin-right:30px;text-align: right;}"
"h1.alarm{text-align:center;font-size: 30px;color:red;font-weight: bolder;}"
"h1.dabiaoti{font-size: 40px;font-weight: bolder;text-align: center;}"
"h1.text_bt{font-size: 30px;font-weight: bolder;text-align: center;border-color: #00FFFF;color: #996666;}"
"h1#daohang{margin-top:7px;margin-bottom:0px;font-size:1.1em;font-weight:normal;padding-left:31px;}"
"h1#txt{margin-top:9px;margin-bottom:2px;font-size:1.0em;font-weight:normal;padding-left:31px;}"
"h2{margin-top:15px;margin-bottom:10px;font-size:1.4em;font-weight:normal;text-align: left;}"
"h3{margin-top:10px;margin-left:30px;margin-bottom:1px;font-size:1.3em;font-weight:normal;text-align: left;}"
"h4{margin-top:15px;margin-right:28px;margin-bottom:8px;font-size:1.4em;font-weight:normal;text-align: right;}"
"h5{margin-top:5px;margin-bottom:5px;color:#575757;font-size:1.3em;font-weight:normal;text-align: center;}"
"h1#lianjie{font-size: 18px;text-align: left;}--></style></head>"
"<body  bgcolor=\"#FFFFFF\">"
"<script src=\"/Web/Souce/Java/file_1.js\"></script>"
"<div class=\"head\">"
"<br/>光一科技股份有限公司<br/> <hr /></div>"
"<div id=\"content\"><div class=\"link_msg\"><br/>"
"<h2>用户:</h2><hr /><h5>" //在这里需要加入脚本信息
"</h5>"
"<br/><hr />"
"<h3 class=\"denglubt\">导航栏</h3>"
"<hr />"
"<h4><a href =\"/Web/Souce/User/User_ALARM.html\"  target=\"event\">状态信息绯荤粺淇℃伅璁剧疆琛ㄦ牸</a></h4>"//这些连接信息全部替换成脚本 由脚本来实现
"<h4><a href =\"/Web/Souce/User/User_SET_MSG.html\"  target =\"event\">参数信息</a></h4>"
"<h4><a href =\"/Web/Souce/User/User_SYS_MSG.html\"  target =\"event\">基本信息 </a></h4><br>"

//"<h4><a href =\"#\" onClick=\"getNews(1)\"  target=\"event\">状态信息</a></h4>"//这些连接信息全部替换成脚本 由脚本来实现
//"<h4><a href =\"#\" onClick=\"getNews(2)\"  target =\"event\">参数信息</a></h4>"
//"<h4><a href =\"#\" onClick=\"getNews(3)\"  target =\"event\">基本信息 </a></h4><br>"

"<hr />"
"<a href=\"/Web/Souce/User/reset/pasword.html\"><h4>修改密码</h4></a>"
"<a href=\"/Web/Souce/User/Sup_User.html\"><h4>管理员</h4></a><hr />"
"</div>"
"<div class=\"txt\">"
"<h1 class=text_bt>AT91 LwIP Test Page&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</h1><hr />"
"<br/>"//连接上也需要加入脚本信息
"<iframe src=\"/Web/Souce/User/User_main_2.html\" name=\"event\" width=\"80%\" margin-left:20% height=425px; scrolling></iframe></div> </div>"
"<div class=\"addmsg\"><br/><br/>"	
"<p><a href=\"http://www.elefirst.com\">"
"光一科技股份有限公司</a></p>"
"<p>地址：江苏省南京市苜蓿园大街77号紫金名门9楼</p><p><a href=\"mailto:service@elefirst.com\">用户服务信箱</a>电话025-84277666 邮编 210007</p><hr />"
"</div></body></html>";
