const unsigned char Web_Sup_User[] =
"<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">"
"<html xmlns=\"http://www.w3.org/1999/xhtml\"> <head><title>光一科技股份有限公司</title>"
"<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\" />"
"<META HTTP-EQUIV=\"pragma\" CONTENT=\"no-cache\">"
"<META HTTP-EQUIV=\"Cache-Control\" CONTENT=\"no-cache, must-revalidate\">"
"<META HTTP-EQUIV=\"expires\" CONTENT=\"Wed, 26 Feb 1997 08:21:57 GMT\">"
"<style type=\"text/css\"><!--"


".sup_user{"
"border-bottom:#fff 20px solid; "
"padding-bottom:10px;"
"width:50%;"
"margin:10% 10% 20% 25%;"
"text-align:center;"
"background-color:#EEFAFF;"
"border: 1px solid #000000;"
"}"
 ".sup_user_head {"
" font-size: 20px; "
" font-weight: bold;"
" background-color: #AEC6FD;"
" text-align: center;"
" height :30px; "
" width: 100%; "
" padding-top:13px;"
" color: #FFFFFF;"
" }"
"-->"
"</style>"
"</head>"

"<body bgcolor=\"#d0d0d0\">"
"<div class=\"sup_user\">"
"<div class=\"sup_user_head\">光一科技股份有限公司</div>"

"<p><h3> 管理员</h3></p><hr/>"
"<form name=\"form\"method=\"post\">"
"账号: <input type=\"#text\" name=\"#sup_user\" />"
"<br/><br/>"
"密码: <input type=\"password\" name=\"#password\">"
"<br/><br/>"
"<input name=\"重置\" type=\"reset\" value=\"取消\" />&nbsp;"
"<input type=\"button\"  onclick=\"sup_user()\"  value=\"登录\" /></h5>"




"</form>"
"<p><h5><a href=\"http://www.elefirst.com/\">光一科技股份有限公司</a></h5></p>"
"<p><h5>地址：江苏省南京市苜蓿园大街77号紫金名门9楼 <br/>电话025-84277666 邮编 210007</h5></p>"
"</div>	"
"</body> "
"</html> " ;




const unsigned char Web_Reset_Password[] =
"<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">"
"<html xmlns=\"http://www.w3.org/1999/xhtml\">"
"<head>"
"<title>光一科技股份有限公司</title>"
"<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\" />"
"<style type=\"text/css\">"
"<!--"
".sup_user{"
"border-bottom:#fff 20px solid;"
"padding-bottom:10px;"
"width:50%;"
"margin:10% 10% 20% 25%;"
"text-align: left;"
"background-color:#EEFAFF;"
"border: 1px solid #000000;"
"}"
 ".sup_user_head {"
	"font-size: 20px;"
	"font-weight: bold;"
	"background-color: #AEC6FD;"
	"text-align: center;"
	"height :30px;"
	"width: 100%;"
	"padding-top:13px;"
	"color: #FFFFFF;"
//	"margin-right: 100px;"
 "}"
  ".sup_user_text{"
	"font-size: 13px;"
	"font-weight: bold;"
	"padding-top:0px;"
	"text-align: center;"
"}"
"-->"
"</style>"
"</head>"

"<body bgcolor=\"#d0d0d0\">"
"<div class=\"sup_user\">"
"<div class=\"sup_user_head\">光一科技股份有限公司</div>"
"<div align=\"center\"><h2> 用户更改密码</h2><hr />"
"</div>"

"<div class=\"sup_user_text\">"
"<form name=\"form\"method=\"post\" >"
"<br/>&nbsp;&nbsp;&nbsp;请输入账号: <input type=\"#text\" name=\"#user\" /><br/>"
"&nbsp;&nbsp;请输入旧密码: <input type=\"#password\" name=\"#password\"><br/>"
"请输入您的新密码: <input type=\"#password\" name=\"#newpassword\"><br/>"
"情再次输入新密码: <input type=\"#password\" name=\"#newpassword\"><br/><br/>"
//"</div>"
//"<div align=\"center\" 	margin-right=100px>"
 "<input name=\"reset\" type=\"reset\"  id=\"reset\" value=\"&nbsp取消&nbsp\" />"
 "&nbsp;&nbsp;&nbsp;&nbsp;<input type=\"submit\" value=\"&nbsp更改&nbsp\" />"
//"</div>"
"</form>"
"</div>"
"<div align=\"center\">"
"<h5><a href=\"http://www.elefirst.com/\">光一科技股份有限公司</a></h5>"
"<h5>地址：江苏省南京市苜蓿园大街77号紫金名门9楼 电话025-84277666 邮编 210007</h5>"
"</div>"
"</div>"
"</body>"
"</html>";


