//系统信息参数栏 1	 不要修改
/*unsigned char Web_SYS_MSAGE_TABLE_HARD[] =
"绯荤粺淇℃伅璁剧疆琛ㄦ牸"
"<table width=\"90%\" border=\"1\" cellspacing=\"1\" cellpadding=\"1\">	"
"<tr>"
    "<th width=\"44\" scope=\"col\">搴忓彿</th>"	
   //<th width=\"44\" scope=\"col\">搴忓彿</th>		
    "<th width=\"47\" scope=\"col\">閫夋嫨</th>"
    "<th width=\"156\" scope=\"col\">鍚嶇О</th>"

    "<th width=\"162\" scope=\"col\">鏈湴鍊?/th>"
    "<th width=\"112\" scope=\"col\">杩滅▼鍊?/th>"
    "<th width=\"119\" scope=\"col\">鏇存柊鏃堕棿</th>"
"</tr>"	; */

unsigned char Web_SYS_MSAGE_TABLE_HARD[] =
  "<table width=\"90%\" border=\"2\" cellpadding=\"1\" cellspacing=\"1\" bordercolor=\"#333333\" bgcolor=\"#999999\" >"
    "<tr class=\"STYLE2\">"
      "<th width=\"6%\" scope=\"col\">搴忓彿</th>"
      "<th width=\"6%\" scope=\"col\">閫夋嫨</th>"
      "<th width=\"24%\" scope=\"col\">鍙傛暟鍚嶇О</th>"
      "<th width=\"23%\" scope=\"col\">鏈湴鍊?/th>"
      "<th width=\"23%\" scope=\"col\">杩滅▼鍊?/th>  "
      "<th width=\"20%\" scope=\"col\">鏇存柊鏃堕棿</th>"
    "</tr>"	;


//系统信息参数栏 2	 不要修改
unsigned char Web_SYS_MSAGE_TABLE_LAST[] =
"</table>";


unsigned char SET_MSG[1];
/*
"<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\""
"\"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">"
"<html xmlns=\"http://www.w3.org/1999/xhtml\"><head>"
"<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\" />"
"<style type=\"text/css\">"
"<!--"
"#content"
"{overflow:hidden;margin: 0 0 0 1.5%;width: 97%;align:right;}"
".txtHint"
"{"
	"color: #006699;"
	"align:center;"
"}"
".STYLE1 {"
	"font-family: \"Times New Roman\", Times, serif;"
	"font-size: 12px;"
	"text-align: center;"
"}"
".STYLE2 {"
	"font-family: Arial, Helvetica, sans-serif;"
	"font-size: 14px;"
"}"
".STYLE3{"
	"font-family: \"Times New Roman\", Times, serif;"
	"font-size: 12px;"
	"text-align: center;"
	"width: 90%;"
"}"
".ANNIU1{"
	"text-align: center;"
	"margin-left:30px;"
"}"
".ANNIU2{"
	"text-align: center;"
	"margin-left:15px;"
"}"
".xuanze{"
	"align:right;"
	"margin-right:15px;"
"}"
"h1{"
	"margin-top:1px;"
	"margin-bottom:5px;"
	"margin-right:15px;"
	"text-align: center;"
	"font-size:20px;"
	"font-weight:normal;"
	"color: #993366;"
"}"
"h2{margin-top:1px;margin-left:30px;color:#575757;font-size:1.1em;font-weight:normal;}"
"h3{margin-top:0px;margin-left:5px;color:#575757;font-size:1.0em;font-weight:normal;}"
"</style>"
"<title>光一科技通讯股份有限公司</title>"
"</head>"
"<body>"
"<script src=\"/Web/Souce/Java/file_1.js\"></script>"
"<div id=\"content\">"
"<h1>系统状态栏</h1><br />"
	"<form name=\"form_button\">参数信息"
 	"<div align=\"left\">"
 	    "<input name=\"Previous\"  type=\"button\" class=\"ANNIU1\" onclick=\"form_button_add\" value=\"上一页\" />"
	    "<input name=\"Next\" type=\"button\"  class=\"ANNIU2\" onclick=\"form_button_sub\" value=\"下一页\" />"
	"</div>"
    "</form>"
"</div>"

"<form action=""  method=\"post\" name=\"myForm\" id=\"myForm\">"

  	"<div align=\"center\" id=\"txtHint\"> </div>"
 	   "<div align=\"center\">"	
	      "<br/><br/>"
    	  "<input name=\"reset\" type=\"reset\"  id=\"reset\" value=\"取消\" />"
   	 	  "<input type=\"button\"  onclick=\"formSubmit_read()\" value=\"查询\" />"
   	 	  "<input type=\"button\"  onclick=\"formSubmit_set()\" value=\"确定\" />"
       "</div>"
"</form>"

	 										
	"<div  align=\"right\" class=\"xuanze\">"
	"<form name=\"form_sel\">"
	  "页码&nbsp;"
      "<select name=\"yema\"  onclick=\"showCustomer(this.value)\" >"
      "<option value=\"001\" selected=\"selected\">第-1-页</option>"
      "<option value=\"002\">第-2-页</option>"
      "<option value=\"003\">第-3-页</option>"
      "<option value=\"004\">第-4-页</option>"
      "<option value=\"005\">第-5-页</option>"
      "<option value=\"006\">第-6-页</option>"
      "<option value=\"007\">第-7-页</option>"
      "<option value=\"008\">第-8-页</option>"
      "<option value=\"009\">第-9-页</option>"
      "<option value=\"010\">第-10-页</option>"
      "<option value=\"011\">第-11-页</option>"
      "<option value=\"012\">第-12-页</option>"
      "<option value=\"013\">第-13-页</option>"
	  "<option value=\"014\">第-14-页</option>"
      "<option value=\"015\">第-15-页</option>"
      "<option value=\"016\">第-16-页</option>"
      "<option value=\"017\">第-17-页</option>"
      "<option value=\"018\">第-18-页</option>"
      "<option value=\"019\">第-19-页</option>"
	  "<option value=\"020\">第-20-页</option>"
    "</select>"	 "</form>"
	"</div>"

"</body>"
"</html>";*/


