
const unsigned char help[] =
"<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">"
"<html xmlns=\"http://www.w3.org/1999/xhtml\"> <head><title>光一科技股份有限公司</title>"
"<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\" />"
"</head><body bgcolor=\"#d0d0d0\">"
"<p><h1 text-align=\"center\">请与管理员联系<br/> </h1></p>"
"</body></html>" ;
unsigned char user_main_2[1];
unsigned char SYS_MSG[] =
"<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\""
"\"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">"
"<html xmlns=\"http://www.w3.org/1999/xhtml\"><head>"
"<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\" />"
"<style type=\"text/css\">"
"<!--"
"#content"
"{overflow:hidden;margin: 0 0 0 1.5%;width: 97%;align:right;}"
".txtHint"
"{"
	"color: #006699;"
	"align:center;"
"}"
".STYLE1 {"
	"font-family: \"Times New Roman\", Times, serif;"
	"font-size: 12px;"
	"text-align: center;"
"}"
".STYLE2 {"
	"font-family: Arial, Helvetica, sans-serif;"
	"font-size: 14px;"
"}"
".STYLE3{"
	"font-family: \"Times New Roman\", Times, serif;"
	"font-size: 12px;"
	"text-align: center;"
	"width: 90%;"
"}"
".ANNIU1{"
	"text-align: center;"
	"margin-left:30px;"
"}"
".ANNIU2{"
	"text-align: center;"
	"margin-left:15px;"
"}"
".xuanze{"
	"align:right;"
	"margin-right:15px;"
"}"
"h1{"
	"margin-top:1px;"
	"margin-bottom:5px;"
	"margin-right:15px;"
	"text-align: center;"
	"font-size:20px;"
	"font-weight:normal;"
	"color: #993366;"
"}"
"h2{margin-top:1px;margin-left:30px;color:#575757;font-size:1.1em;font-weight:normal;}"
"h3{margin-top:0px;margin-left:5px;color:#575757;font-size:1.0em;font-weight:normal;}"
"</style>"
"<title>光一科技通讯股份有限公司</title>"
"</head>"
"<body>"
"<script src=\"/Web/Souce/Java/file_1.js\"></script>"
"<div id=\"content\">"
"<h1>系统状态栏</h1><br />"
	/*"<form >*/
	"基本信息"
 	"<div align=\"left\">"
		"<script type=\"text/javascript\">"
		"FORM_Display_Bufften();"
		"</script>"
 	    "<input name=\"customers\" id=\"next\"  type=\"button\" class=\"ANNIU1\" onclick=\"FORM_SUB()\" value=\"上一页\" />"
	    "<input name=\"customers\" id=\"Previous\" type=\"button\"  class=\"ANNIU2\" onclick=\"FORM_ADD()\" value=\"下一页\" />"
	"</div>"        														 				
    "</form>"
"</div>"

"<form action=""  method=\"post\" name=\"myForm\" id=\"myForm\">"

  	"<div align=\"center\" id=\"txtHint\"> </div>"
 	   "<div align=\"center\">"	
	      "<br/><br/>"
    	  "<input name=\"reset\" type=\"reset\"  id=\"reset\" value=\"取消\" />"
   	 	  "<input type=\"button\"  onclick=\"formSubmit_read()\" value=\"查询\" />"
   	 	  "<input type=\"button\"  onclick=\"formSubmit_set()\" value=\"确定\" />"
       "</div>"
"</form>"
	"<form action=""   name=\"FID_Form\" id=\"FID_Form\">"
  	
		"<div  align=\"right\" class=\"xuanze\">"

	 		"页码&nbsp;"
      		"<select name=\"customers\"  onclick=\"showCustomer(this.value)\" >"
			      "<option value='1' selected=\"selected\">第-1-页</option>"
			      "<option value=2>第-2-页</option>"
			      "<option value=3>第-3-页</option>"
			      "<option value=4>第-4-页</option>"
			      "<option value=5>第-5-页</option>"
			      "<option value=6>第-6-页</option>"
			      "<option value=7>第-7-页</option>"
			      "<option value=8>第-8-页</option>"
			      "<option value=9>第-9-页</option>"
			      "<option value=10>第-10-页</option>"
			      "<option value=11>第-11-页</option>"
			      "<option value=12>第-12-页</option>"
			      "<option value=13>第-13-页</option>"
				  "<option value=14>第-14-页</option>"
			      "<option value=015>第-15-页</option>"
			      "<option value=16>第-16-页</option>"
			      "<option value=17>第-17-页</option>"
			      "<option value=18>第-18-页</option>"
			      "<option value=19>第-19-页</option>"
				  "<option value=20>第-20-页</option>"
    		"</select>"
		"</div>"			
	"</form>"
"</body>"
"</html>";







