/******************************************************************************************************
* 2013-2014 益邦科技有限公司
* 文件名: 
* 创建人: 王一凡
* 日　期: 2013/09/21
* 修改人: 
* 日　期: 
* 描　述: 
* 版　本: V1.0
*****************************************************************************************************/
#include "MemData.h"
#include "MemDrv.h"



/**************************************************************************************************
                                        数据存储偏移信息
***************************************************************************************************/
//1.测量点实时数据
const MEM_OFF_INFO	g_sMpRealDataOff[] = 
{
	MEM_OFF_INFO_DEFINE(F1, pMEM_MP_REAL_DATA, nMeterAddr),
	MEM_OFF_INFO_DEFINE(F2, pMEM_MP_REAL_DATA, nReadTime[0]),
	MEM_OFF_INFO_DEFINE(F3, pMEM_MP_REAL_DATA, nDate[0]),
	MEM_OFF_INFO_DEFINE(F4, pMEM_MP_REAL_DATA, nTime[0]),

	MEM_OFF_INFO_DEFINE(F5, pMEM_MP_REAL_DATA, nEnergyPP[0]),
	MEM_OFF_INFO_DEFINE(F6, pMEM_MP_REAL_DATA, nEnergyNP[0]),
	MEM_OFF_INFO_DEFINE(F7, pMEM_MP_REAL_DATA, nEnergyPN[0]),
	MEM_OFF_INFO_DEFINE(F8, pMEM_MP_REAL_DATA, nEnergyNN[0]),
	MEM_OFF_INFO_DEFINE(F9, pMEM_MP_REAL_DATA, nQ1Energy[0]),
	MEM_OFF_INFO_DEFINE(F10, pMEM_MP_REAL_DATA, nQ2Energy[0]),
	MEM_OFF_INFO_DEFINE(F11, pMEM_MP_REAL_DATA, nQ3Energy[0]),
	MEM_OFF_INFO_DEFINE(F12, pMEM_MP_REAL_DATA, nQ4Energy[0]),
	MEM_OFF_INFO_DEFINE(F13, pMEM_MP_REAL_DATA, nPPDemand[0]),
	MEM_OFF_INFO_DEFINE(F14, pMEM_MP_REAL_DATA, nNPDemand[0]),
	MEM_OFF_INFO_DEFINE(F15, pMEM_MP_REAL_DATA, nPNDemand[0]),
	MEM_OFF_INFO_DEFINE(F16, pMEM_MP_REAL_DATA, nNNDemand[0]),
	MEM_OFF_INFO_DEFINE(F17, pMEM_MP_REAL_DATA, nVolt[0]),
	MEM_OFF_INFO_DEFINE(F18, pMEM_MP_REAL_DATA, nCurr[0]),
	MEM_OFF_INFO_DEFINE(F19, pMEM_MP_REAL_DATA, nPWatt[0]),
	MEM_OFF_INFO_DEFINE(F20, pMEM_MP_REAL_DATA, nNWatt[0]),
	MEM_OFF_INFO_DEFINE(F21, pMEM_MP_REAL_DATA, nSWatt[0]),
	MEM_OFF_INFO_DEFINE(F22, pMEM_MP_REAL_DATA, nFactor[0]),
	
	{FEND, 1, 0, sizeof(MEM_MP_REAL_DATA), 0}
};

//2.测量点日数据
const MEM_OFF_INFO	g_sMpDayDataOff[] = 
{
	MEM_OFF_INFO_DEFINE(F1, pMEM_MP_DAY_DATA, nMeterAddr[0]),
	MEM_OFF_INFO_DEFINE(F2, pMEM_MP_DAY_DATA, sDataTime[0]),
	MEM_OFF_INFO_DEFINE(F3, pMEM_MP_DAY_DATA, nReadTime[0]),
	
	MEM_OFF_INFO_DEFINE(F4, pMEM_MP_DAY_DATA, nDEnergyPP[0]),
	MEM_OFF_INFO_DEFINE(F5, pMEM_MP_DAY_DATA, nDEnergyNP[0]),
	MEM_OFF_INFO_DEFINE(F6, pMEM_MP_DAY_DATA, nDEnergyPN[0]),
	MEM_OFF_INFO_DEFINE(F7, pMEM_MP_DAY_DATA, nDEnergyNN[0]),
	MEM_OFF_INFO_DEFINE(F8, pMEM_MP_DAY_DATA, nDQ1Energy[0]),
	MEM_OFF_INFO_DEFINE(F9, pMEM_MP_DAY_DATA, nDQ2Energy[0]),
	MEM_OFF_INFO_DEFINE(F10, pMEM_MP_DAY_DATA, nDQ3Energy[0]),
	MEM_OFF_INFO_DEFINE(F11, pMEM_MP_DAY_DATA, nDQ4Energy[0]),
	MEM_OFF_INFO_DEFINE(F12, pMEM_MP_DAY_DATA, nDPPDemand[0]),
	MEM_OFF_INFO_DEFINE(F13, pMEM_MP_DAY_DATA, nDNPDemand[0]),
	MEM_OFF_INFO_DEFINE(F14, pMEM_MP_DAY_DATA, nDPNDemand[0]),
	MEM_OFF_INFO_DEFINE(F15, pMEM_MP_DAY_DATA, nDNNDemand[0]),
	
	{FEND, 1, 0, sizeof(MEM_MP_DAY_DATA), 0}
};


//3.测量点月数据
const MEM_OFF_INFO	g_sMpMonDataOff[] = 
{
	MEM_OFF_INFO_DEFINE(F1, pMEM_MP_MON_DATA, nMeterAddr),
	MEM_OFF_INFO_DEFINE(F2, pMEM_MP_MON_DATA, sDataTime[0]),
	MEM_OFF_INFO_DEFINE(F3, pMEM_MP_MON_DATA, nReadTime[0]),
	
	MEM_OFF_INFO_DEFINE(F4, pMEM_MP_MON_DATA, nMEnergyPP[0]),
	MEM_OFF_INFO_DEFINE(F5, pMEM_MP_MON_DATA, nMEnergyNP[0]),
	MEM_OFF_INFO_DEFINE(F6, pMEM_MP_MON_DATA, nMEnergyPN[0]),
	MEM_OFF_INFO_DEFINE(F7, pMEM_MP_MON_DATA, nMEnergyNN[0]),
	MEM_OFF_INFO_DEFINE(F8, pMEM_MP_MON_DATA, nMQ1Energy[0]),
	MEM_OFF_INFO_DEFINE(F9, pMEM_MP_MON_DATA, nMQ2Energy[0]),
	MEM_OFF_INFO_DEFINE(F10, pMEM_MP_MON_DATA, nMQ3Energy[0]),
	MEM_OFF_INFO_DEFINE(F11, pMEM_MP_MON_DATA, nMQ4Energy[0]),
	MEM_OFF_INFO_DEFINE(F12, pMEM_MP_MON_DATA, nMPPDemand[0]),
	MEM_OFF_INFO_DEFINE(F13, pMEM_MP_MON_DATA, nMNPDemand[0]),
	MEM_OFF_INFO_DEFINE(F14, pMEM_MP_MON_DATA, nMPNDemand[0]),
	MEM_OFF_INFO_DEFINE(F15, pMEM_MP_MON_DATA, nMNNDemand[0]),
	
	{FEND, 1, 0, sizeof(MEM_MP_MON_DATA), 0}
};

//4.测量点曲线数据
const MEM_OFF_INFO	g_sMpCrvDataOff[] = 
{
	MEM_OFF_INFO_DEFINE(F1, pMEM_MP_CRV_DATA, nMeterAddr),
	MEM_OFF_INFO_DEFINE(F2, pMEM_MP_CRV_DATA, sDataTime[0]),
	MEM_OFF_INFO_DEFINE(F3, pMEM_MP_CRV_DATA, nCrvEnergyPP[0]),
	
	MEM_OFF_INFO_DEFINE(F4, pMEM_MP_CRV_DATA, nCrvEnergyNP[0]),
	MEM_OFF_INFO_DEFINE(F5, pMEM_MP_CRV_DATA, nCrvEnergyPN[0]),
	MEM_OFF_INFO_DEFINE(F6, pMEM_MP_CRV_DATA, nCrvEnergyNN[0]),
	
	MEM_OFF_INFO_DEFINE(F7, pMEM_MP_CRV_DATA, nCrvVolt[0]),
	MEM_OFF_INFO_DEFINE(F8, pMEM_MP_CRV_DATA, nCrvCurr[0]),
	MEM_OFF_INFO_DEFINE(F9, pMEM_MP_CRV_DATA, nCrvPWatt[0]),
	MEM_OFF_INFO_DEFINE(F10, pMEM_MP_CRV_DATA, nCrvNWatt[0]),
	MEM_OFF_INFO_DEFINE(F11, pMEM_MP_CRV_DATA, nCrvSWatt[0]),
	MEM_OFF_INFO_DEFINE(F12, pMEM_MP_CRV_DATA, nCrvFactor[0]),
	
	{FEND, 1, 0, sizeof(MEM_MP_CRV_DATA), 0}
};

//5.测量点抄表日数据
const MEM_OFF_INFO	g_sMpRDayDataOff[] = 
{
	MEM_OFF_INFO_DEFINE(F1, pMEM_MP_RDAY_DATA, nMeterAddr),
	MEM_OFF_INFO_DEFINE(F2, pMEM_MP_RDAY_DATA, sDataTime[0]),
	
	MEM_OFF_INFO_DEFINE(F3, pMEM_MP_RDAY_DATA, nRDEnergyPP[0]),
	MEM_OFF_INFO_DEFINE(F4, pMEM_MP_RDAY_DATA, nRDEnergyNP[0]),
	MEM_OFF_INFO_DEFINE(F5, pMEM_MP_RDAY_DATA, nRDEnergyPN[0]),
	MEM_OFF_INFO_DEFINE(F6, pMEM_MP_RDAY_DATA, nRDEnergyNN[0]),
	
	{FEND, 1, 0, sizeof(MEM_MP_RDAY_DATA), 0}
};


//4.RAM临时交互区
const MEM_OFF_INFO	g_sXRamDataOff[] = 
{
	MEM_OFF_INFO_DEFINE(F1, pMEM_X_RAM_DATA, nRs485Real),
	MEM_OFF_INFO_DEFINE(F2, pMEM_X_RAM_DATA, nRs485Day),
	MEM_OFF_INFO_DEFINE(F3, pMEM_X_RAM_DATA, nRs485Mon),
	MEM_OFF_INFO_DEFINE(F4, pMEM_X_RAM_DATA, nRs485Crv),
    MEM_OFF_INFO_DEFINE(F5, pMEM_X_RAM_DATA, nResetFlg),
    MEM_OFF_INFO_DEFINE_EXT(F6, MAX_TURN_NUM, pMEM_X_RAM_DATA, nTripFlg[0]),
    MEM_OFF_INFO_DEFINE_EXT(F7, MAX_TURN_NUM, pMEM_X_RAM_DATA, nLockFlg[0]),
    MEM_OFF_INFO_DEFINE(F8, pMEM_X_RAM_DATA, nRmotSigl),
    MEM_OFF_INFO_DEFINE(F9, pMEM_X_RAM_DATA, nLinkReq),
    
    MEM_OFF_INFO_DEFINE(F10, pMEM_X_RAM_DATA, sAcFreeze),
    MEM_OFF_INFO_DEFINE(F11, pMEM_X_RAM_DATA, sAcInit),
    MEM_OFF_INFO_DEFINE(F12, pMEM_X_RAM_DATA, sAcEvent[0]),
    
    MEM_OFF_INFO_DEFINE(F13, pMEM_X_RAM_DATA, nRdMtProtFlg),
	{FEND, 1, 0, sizeof(MEM_X_RAM_DATA), 0}
};


//5.FLASH临时交互区
const MEM_OFF_INFO	g_sXFlhDataOff[] =
{
	MEM_OFF_INFO_DEFINE(F1, pMEM_X_FLH_DATA, nRealNext),
	MEM_OFF_INFO_DEFINE(F2, pMEM_X_FLH_DATA, sDayMemInfo),	
	MEM_OFF_INFO_DEFINE(F3, pMEM_X_FLH_DATA, sMonMemInfo),
	MEM_OFF_INFO_DEFINE(F4, pMEM_X_FLH_DATA, sCrvMemInfo),	
	MEM_OFF_INFO_DEFINE(F5, pMEM_X_FLH_DATA, sRDayMemInfo),
    
    MEM_OFF_INFO_DEFINE(F6, pMEM_X_FLH_DATA, sRcEvtInfo),
    MEM_OFF_INFO_DEFINE_EXT(F7, MAX_RC_EVT_NUM, pMEM_X_FLH_DATA, sRcEvtData[0]),
    MEM_OFF_INFO_DEFINE(F8, pMEM_X_FLH_DATA, nACRunStat[0]),
	{FEND, 1, 0, sizeof(MEM_X_FLH_DATA), 0}
};


//6.FRAM临时交互区
const MEM_OFF_INFO	g_sXFramDataOff[] =
{
    MEM_OFF_INFO_DEFINE(F1, pMEM_X_FRAM_DATA, nFileInitFlg),	
	MEM_OFF_INFO_DEFINE(F2, pMEM_X_FRAM_DATA, sTermClk),	
    MEM_OFF_INFO_DEFINE(F3, pMEM_X_FRAM_DATA, nPulseNum),
    //MEM_OFF_INFO_DEFINE(F4, pMEM_X_FRAM_DATA, nTimes),
	{FEND, 1, 0, sizeof(MEM_X_FRAM_DATA), 0}
};


//交采数据
//交采瞬时数据 
const MEM_OFF_INFO	g_sACInstDataOff[] =
{
    MEM_OFF_INFO_DEFINE(F1, pMEM_AC_INST_DATA, sData),	
	//MEM_OFF_INFO_DEFINE(F2, pMEM_AC_INST_DATA, sSyncData),	
    MEM_OFF_INFO_DEFINE(F3, pMEM_AC_INST_DATA, sAver),
	{FEND, 1, 0, sizeof(MEM_AC_INST_DATA), 0}
};

//交采实时数据
const MEM_OFF_INFO	g_sACRealDataOff[] =
{
    MEM_OFF_INFO_DEFINE(F1, pMEM_AC_REAL_DATA, sAcEnergy),
    MEM_OFF_INFO_DEFINE(F2, pMEM_AC_REAL_DATA, sAcQEnergy),
	MEM_OFF_INFO_DEFINE(F3, pMEM_AC_REAL_DATA, sAcTriEnergy),	
    MEM_OFF_INFO_DEFINE(F4, pMEM_AC_REAL_DATA, sAcTriQEnergy),	
    MEM_OFF_INFO_DEFINE(F5, pMEM_AC_REAL_DATA, sAcCombEnergy),	
    MEM_OFF_INFO_DEFINE(F6, pMEM_AC_REAL_DATA, nENChkSum),
    MEM_OFF_INFO_DEFINE(F7, pMEM_AC_REAL_DATA, sAcDemand),	
    MEM_OFF_INFO_DEFINE(F8, pMEM_AC_REAL_DATA, sAcQDemand),
    MEM_OFF_INFO_DEFINE(F9, pMEM_AC_REAL_DATA, sEPulse[0]),	
    MEM_OFF_INFO_DEFINE(F10, pMEM_AC_REAL_DATA, sPhEPulse[0]),	
    MEM_OFF_INFO_DEFINE(F11, pMEM_AC_REAL_DATA, sPhQEPulse[0]),
    MEM_OFF_INFO_DEFINE(F12, pMEM_AC_REAL_DATA, sCombEPulse),	
    MEM_OFF_INFO_DEFINE(F13, pMEM_AC_REAL_DATA, nAcDemand[0][0]),
    MEM_OFF_INFO_DEFINE(F14, pMEM_AC_REAL_DATA, nVer[0]),
    MEM_OFF_INFO_DEFINE(F15, pMEM_AC_REAL_DATA, sAcDamage),// Damage变损 
    MEM_OFF_INFO_DEFINE(F16, pMEM_AC_REAL_DATA, sAcFirmLoss),// 固损 Firm Loss    
    MEM_OFF_INFO_DEFINE(F17, pMEM_AC_REAL_DATA, sAcCopperLoss),// 铜损 Copper loss
    MEM_OFF_INFO_DEFINE(F18, pMEM_AC_REAL_DATA, sAcIronLoss),// 铁损 Iron loss
    
	{FEND, 1, 0, sizeof(MEM_AC_REAL_DATA), 0}
};


#if 0
//交采实时数据
const MEM_OFF_INFO	g_sACRealDataOff[] =
{
    MEM_OFF_INFO_DEFINE(F1, pMEM_AC_REAL_DATA, sAcEnergy),
    MEM_OFF_INFO_DEFINE(F2, pMEM_AC_REAL_DATA, sAcQEnergy),
	MEM_OFF_INFO_DEFINE(F3, pMEM_AC_REAL_DATA, sAcTriEnergy),	
    MEM_OFF_INFO_DEFINE(F4, pMEM_AC_REAL_DATA, sAcTriQEnergy),	
    MEM_OFF_INFO_DEFINE(F5, pMEM_AC_REAL_DATA, sEPulse[0]),	
    MEM_OFF_INFO_DEFINE(F6, pMEM_AC_REAL_DATA, sPhEPulse[0]),	
    MEM_OFF_INFO_DEFINE(F7, pMEM_AC_REAL_DATA, sPhQEPulse[0]),	
    MEM_OFF_INFO_DEFINE(F8, pMEM_AC_REAL_DATA, nEnergyCrc),	
    
    MEM_OFF_INFO_DEFINE(F9, pMEM_AC_REAL_DATA, sAcLoserEnergy),	
    MEM_OFF_INFO_DEFINE(F10, pMEM_AC_REAL_DATA, sLoserAccuData),	
    MEM_OFF_INFO_DEFINE(F11, pMEM_AC_REAL_DATA, nLoserCrc),	
    MEM_OFF_INFO_DEFINE(F12, pMEM_AC_REAL_DATA, sAcDemand),	
    MEM_OFF_INFO_DEFINE(F13, pMEM_AC_REAL_DATA, sAcQDemand),	
    MEM_OFF_INFO_DEFINE(F14, pMEM_AC_REAL_DATA, fAcDemand[0][0]),	
    MEM_OFF_INFO_DEFINE(F15, pMEM_AC_REAL_DATA, nDemandCrc),	
    MEM_OFF_INFO_DEFINE(F16, pMEM_AC_REAL_DATA, nVer[0]),
        
	{FEND, 1, 0, sizeof(MEM_AC_REAL_DATA), 0}
};
#endif

//交采实时数据备份
const MEM_OFF_INFO	g_sACRealBackOff[] =
{
    MEM_OFF_INFO_DEFINE(F1, pMEM_AC_REAL_BACK, sAcEnergy),
    MEM_OFF_INFO_DEFINE(F2, pMEM_AC_REAL_BACK, sAcQEnergy),
	MEM_OFF_INFO_DEFINE(F3, pMEM_AC_REAL_BACK, sAcTriEnergy),	
    MEM_OFF_INFO_DEFINE(F4, pMEM_AC_REAL_BACK, sAcTriQEnergy),	
    MEM_OFF_INFO_DEFINE(F5, pMEM_AC_REAL_BACK, sEPulse[0]),	
    MEM_OFF_INFO_DEFINE(F6, pMEM_AC_REAL_BACK, sPhEPulse[0]),	
    MEM_OFF_INFO_DEFINE(F7, pMEM_AC_REAL_BACK, sPhQEPulse[0]),	
    MEM_OFF_INFO_DEFINE(F8, pMEM_AC_REAL_BACK, nEnergyCrc),	
    
	{FEND, 1, 0, sizeof(MEM_AC_REAL_BACK), 0}
};

#if 0
//交采日数据
const MEM_OFF_INFO	g_sACDayDataOff[] =
{
    MEM_OFF_INFO_DEFINE(F1, pMEM_AC_DAY_DATA, sAcEnergy),	
    MEM_OFF_INFO_DEFINE(F2, pMEM_AC_DAY_DATA, sAcQEnergy),
    MEM_OFF_INFO_DEFINE(F3, pMEM_AC_DAY_DATA, sAcTriEnergy),
    MEM_OFF_INFO_DEFINE(F4, pMEM_AC_DAY_DATA, sAcTriQEnergy),
    MEM_OFF_INFO_DEFINE(F5, pMEM_AC_DAY_DATA, sAcDemand),
    MEM_OFF_INFO_DEFINE(F6, pMEM_AC_DAY_DATA, sAcQDemand),
    MEM_OFF_INFO_DEFINE(F7, pMEM_AC_DAY_DATA, sRealP[0]),
    MEM_OFF_INFO_DEFINE(F8, pMEM_AC_DAY_DATA, sRealQ[0]),
    MEM_OFF_INFO_DEFINE(F9, pMEM_AC_DAY_DATA, sTime),
	{FEND, 1, 0, sizeof(MEM_AC_DAY_DATA), 0}
};

//交采结算日数据
const MEM_OFF_INFO	g_sACRDayDataOff[] =
{
    MEM_OFF_INFO_DEFINE(F1, pMEM_AC_RDAY_DATA, sAcEnergy),	
    MEM_OFF_INFO_DEFINE(F2, pMEM_AC_RDAY_DATA, sAcQEnergy),
    MEM_OFF_INFO_DEFINE(F3, pMEM_AC_RDAY_DATA, sAcTriEnergy),
    MEM_OFF_INFO_DEFINE(F4, pMEM_AC_RDAY_DATA, sAcTriQEnergy),
    MEM_OFF_INFO_DEFINE(F5, pMEM_AC_RDAY_DATA, sAcDemand),
    MEM_OFF_INFO_DEFINE(F6, pMEM_AC_RDAY_DATA, sAcQDemand),
    MEM_OFF_INFO_DEFINE(F7, pMEM_AC_RDAY_DATA, sRealP[0]),
    MEM_OFF_INFO_DEFINE(F8, pMEM_AC_RDAY_DATA, sRealQ[0]),
    MEM_OFF_INFO_DEFINE(F9, pMEM_AC_RDAY_DATA, sTime),
	{FEND, 1, 0, sizeof(MEM_AC_RDAY_DATA), 0}
};

//交采冻结数据
const MEM_OFF_INFO	g_sACDjDataOff[] =
{
    MEM_OFF_INFO_DEFINE(F1, pMEM_AC_DJ_DATA, sAcEnergy),
    MEM_OFF_INFO_DEFINE(F2, pMEM_AC_DJ_DATA, sAcQEnergy),
    MEM_OFF_INFO_DEFINE(F3, pMEM_AC_DJ_DATA, sAcDemand),
    MEM_OFF_INFO_DEFINE(F4, pMEM_AC_DJ_DATA, sRealP[0]),
    MEM_OFF_INFO_DEFINE(F5, pMEM_AC_DJ_DATA, sRealQ[0]),
    MEM_OFF_INFO_DEFINE(F6, pMEM_AC_DJ_DATA, sTime),

	{FEND, 1, 0, sizeof(pMEM_AC_DJ_DATA), 0}
};
#endif
    
//历史数据
const MEM_OFF_INFO	g_sACHistDataOff[] =
{
    MEM_OFF_INFO_DEFINE_EXT(F1, MAX_AC_DAY_DATA_NUM,    pMEM_AC_HIST_DATA, sDayData[0]),
    MEM_OFF_INFO_DEFINE_EXT(F2, MAX_AC_RDAY_DATA_NUM,   pMEM_AC_HIST_DATA, sRdDayData[0]),
    MEM_OFF_INFO_DEFINE_EXT(F3, MAX_AC_SSDJ_DATA_NUM,   pMEM_AC_HIST_DATA, sSsdjData[0]),
    MEM_OFF_INFO_DEFINE_EXT(F4, MAX_AC_DSDJ_DATA_NUM,   pMEM_AC_HIST_DATA, sDsdjData[0]),
    MEM_OFF_INFO_DEFINE_EXT(F5, MAX_AC_SQDJ_DATA_NUM,   pMEM_AC_HIST_DATA, sSqdjData[0]),
    MEM_OFF_INFO_DEFINE_EXT(F6, MAX_AC_SDDJ_DATA_NUM,   pMEM_AC_HIST_DATA, sSddjData[0]),
    MEM_OFF_INFO_DEFINE_EXT(F7, MAX_AC_MON_DATA_NUM,    pMEM_AC_HIST_DATA, sMonDayData[0]),
    MEM_OFF_INFO_DEFINE_EXT(F8, 1,    pMEM_AC_HIST_DATA, sNULLDayData[0]), //空闲数据
    {FEND, 1, 0, sizeof(pMEM_AC_HIST_DATA), 0}
};

//事件数据
const MEM_OFF_INFO	g_sACEvtDataOff[] =
{
    MEM_OFF_INFO_DEFINE_EXT(F1, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtSyA[0]),
    MEM_OFF_INFO_DEFINE_EXT(F2, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtSyB[0]),
    MEM_OFF_INFO_DEFINE_EXT(F3, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtSyC[0]),
    MEM_OFF_INFO_DEFINE_EXT(F4, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtDxA[0]),
    MEM_OFF_INFO_DEFINE_EXT(F5, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtDxB[0]),
    MEM_OFF_INFO_DEFINE_EXT(F6, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtDxC[0]),
    MEM_OFF_INFO_DEFINE_EXT(F7, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtQsy[0]),
    MEM_OFF_INFO_DEFINE_EXT(F8, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtDynx[0]),
    MEM_OFF_INFO_DEFINE_EXT(F9, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtSlA[0]),
    MEM_OFF_INFO_DEFINE_EXT(F10, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtSlB[0]),
    MEM_OFF_INFO_DEFINE_EXT(F11, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtSlC[0]),
    MEM_OFF_INFO_DEFINE_EXT(F12, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtDd[0]),
    MEM_OFF_INFO_DEFINE_EXT(F13, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtXlql[0]),
    MEM_OFF_INFO_DEFINE_EXT(F14, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtDbql[0]),
    MEM_OFF_INFO_DEFINE_EXT(F15, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtSjql[0]),
    MEM_OFF_INFO_DEFINE_EXT(F16, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtBc[0]),
    MEM_OFF_INFO_DEFINE_EXT(F17, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtJs[0]),
    
    MEM_OFF_INFO_DEFINE_EXT(F18, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtGyA[0]),
    MEM_OFF_INFO_DEFINE_EXT(F19, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtGyB[0]),
    MEM_OFF_INFO_DEFINE_EXT(F20, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtGyC[0]),
    
    MEM_OFF_INFO_DEFINE_EXT(F21, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtGlA[0]),
    MEM_OFF_INFO_DEFINE_EXT(F22, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtGlB[0]),
    MEM_OFF_INFO_DEFINE_EXT(F23, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtGlC[0]),
    
    MEM_OFF_INFO_DEFINE_EXT(F24, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtClA[0]),
    MEM_OFF_INFO_DEFINE_EXT(F25, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtClB[0]),
    MEM_OFF_INFO_DEFINE_EXT(F26, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtClC[0]),
    
    MEM_OFF_INFO_DEFINE_EXT(F27, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtGzA[0]),
    MEM_OFF_INFO_DEFINE_EXT(F28, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtGzB[0]),
    MEM_OFF_INFO_DEFINE_EXT(F29, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtGzC[0]),
    
    MEM_OFF_INFO_DEFINE_EXT(F30, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtKG[0]),
    
    MEM_OFF_INFO_DEFINE_EXT(F31, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtTZ[0]),//跳闸事件
    MEM_OFF_INFO_DEFINE_EXT(F32, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtHZ[0]),//合闸事件
    MEM_OFF_INFO_DEFINE_EXT(F33, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtMY[0]),//密钥事件
    MEM_OFF_INFO_DEFINE_EXT(F34, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtFH[0]),//负荷开关事件
    MEM_OFF_INFO_DEFINE_EXT(F35, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtDY[0]),//电源异常事件
    MEM_OFF_INFO_DEFINE_EXT(F36, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtSZ[0]),//时钟故障事件
    MEM_OFF_INFO_DEFINE_EXT(F37, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtJL[0]),//时钟故障事件
    MEM_OFF_INFO_DEFINE_EXT(F38, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtglA[0]),
    MEM_OFF_INFO_DEFINE_EXT(F39, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtglB[0]),
    MEM_OFF_INFO_DEFINE_EXT(F40, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtglC[0]),
    MEM_OFF_INFO_DEFINE_EXT(F41, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtBSKG[0]),//OAD开盖
    MEM_OFF_INFO_DEFINE_EXT(F42, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtBSTZ[0]),//OAD跳闸事件
    MEM_OFF_INFO_DEFINE_EXT(F43, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtBSHZ[0]),//OAD合闸事件
    MEM_OFF_INFO_DEFINE_EXT(F44, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtBSMY[0]),//OAD密钥事件
    MEM_OFF_INFO_DEFINE_EXT(F45, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtBSFH[0]),//OAD负荷开关事件
    MEM_OFF_INFO_DEFINE_EXT(F46, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtBSDY[0]),//OAD电源异常事件
    MEM_OFF_INFO_DEFINE_EXT(F47, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtBSSZ[0]),//OAD时钟故障事件
    MEM_OFF_INFO_DEFINE_EXT(F48, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtBSJL[0]),//OAD计量
    
    MEM_OFF_INFO_DEFINE_EXT(F49, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtQyA[0]), //欠压2022.10.18
    MEM_OFF_INFO_DEFINE_EXT(F50, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtQyB[0]),
    MEM_OFF_INFO_DEFINE_EXT(F51, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtQyC[0]),
    
    MEM_OFF_INFO_DEFINE_EXT(F52, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtDlA[0]), //断流2022.10.18
    MEM_OFF_INFO_DEFINE_EXT(F53, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtDlB[0]),
    MEM_OFF_INFO_DEFINE_EXT(F54, MAX_AC_EVT_DATA_NUM, pMEM_AC_EVT, sACEvtDlC[0]),
	{FEND, 1, 0, sizeof(MEM_AC_EVT), 0}
};

//(FRAM备份)交互数据
const MEM_OFF_INFO g_sACBackDataOff[] =
{
    MEM_OFF_INFO_DEFINE(F1, pMEM_AC_BACK_DATA, nSyTime),
    MEM_OFF_INFO_DEFINE(F2, pMEM_AC_BACK_DATA, nAxsyTime),
    MEM_OFF_INFO_DEFINE(F3, pMEM_AC_BACK_DATA, nBxsyTime),
    MEM_OFF_INFO_DEFINE(F4, pMEM_AC_BACK_DATA, nCxsyTime),
    MEM_OFF_INFO_DEFINE(F5, pMEM_AC_BACK_DATA, nAxdxTime),
    MEM_OFF_INFO_DEFINE(F6, pMEM_AC_BACK_DATA, nBxdxTime),
    MEM_OFF_INFO_DEFINE(F7, pMEM_AC_BACK_DATA, nCxdxTime),
    MEM_OFF_INFO_DEFINE(F8, pMEM_AC_BACK_DATA, nQsyTime),
    MEM_OFF_INFO_DEFINE(F9, pMEM_AC_BACK_DATA, nDynxTime),
    MEM_OFF_INFO_DEFINE(F10, pMEM_AC_BACK_DATA, nAxslTime),
    MEM_OFF_INFO_DEFINE(F11, pMEM_AC_BACK_DATA, nBxslTime),
    MEM_OFF_INFO_DEFINE(F12, pMEM_AC_BACK_DATA, nCxslTime),
    MEM_OFF_INFO_DEFINE(F13, pMEM_AC_BACK_DATA, sEventStat),
    
	
	MEM_OFF_INFO_DEFINE(F14, pMEM_AC_BACK_DATA, nGyTime),
    MEM_OFF_INFO_DEFINE(F15, pMEM_AC_BACK_DATA, nAxgyTime),
    MEM_OFF_INFO_DEFINE(F16, pMEM_AC_BACK_DATA, nBxgyTime),
    MEM_OFF_INFO_DEFINE(F17, pMEM_AC_BACK_DATA, nCxgyTime),
    
    MEM_OFF_INFO_DEFINE(F18, pMEM_AC_BACK_DATA, nGlTime),
    MEM_OFF_INFO_DEFINE(F19, pMEM_AC_BACK_DATA, nAxglTime),
    MEM_OFF_INFO_DEFINE(F20, pMEM_AC_BACK_DATA, nBxglTime),
    MEM_OFF_INFO_DEFINE(F21, pMEM_AC_BACK_DATA, nCxglTime),
    
    MEM_OFF_INFO_DEFINE(F22, pMEM_AC_BACK_DATA, nClTime),
    MEM_OFF_INFO_DEFINE(F23, pMEM_AC_BACK_DATA, nAxclTime),
    MEM_OFF_INFO_DEFINE(F24, pMEM_AC_BACK_DATA, nBxclTime),
    MEM_OFF_INFO_DEFINE(F25, pMEM_AC_BACK_DATA, nCxclTime),
    
    MEM_OFF_INFO_DEFINE(F26, pMEM_AC_BACK_DATA, nGzTime),
    MEM_OFF_INFO_DEFINE(F27, pMEM_AC_BACK_DATA, nAxgzTime),
    MEM_OFF_INFO_DEFINE(F28, pMEM_AC_BACK_DATA, nBxgzTime),
    MEM_OFF_INFO_DEFINE(F29, pMEM_AC_BACK_DATA, nCxgzTime),
    
    MEM_OFF_INFO_DEFINE(F30, pMEM_AC_BACK_DATA, sTermClk),
    
    MEM_OFF_INFO_DEFINE(F31, pMEM_AC_BACK_DATA, nQyTime),
    MEM_OFF_INFO_DEFINE(F32, pMEM_AC_BACK_DATA, nAxqyTime),
    MEM_OFF_INFO_DEFINE(F33, pMEM_AC_BACK_DATA, nBxqyTime),
    MEM_OFF_INFO_DEFINE(F34, pMEM_AC_BACK_DATA, nCxqyTime),
    
    MEM_OFF_INFO_DEFINE(F35, pMEM_AC_BACK_DATA, nDlTime),
    MEM_OFF_INFO_DEFINE(F36, pMEM_AC_BACK_DATA, nAxDlTime),
    MEM_OFF_INFO_DEFINE(F37, pMEM_AC_BACK_DATA, nBxDlTime),
    MEM_OFF_INFO_DEFINE(F38, pMEM_AC_BACK_DATA, nCxDlTime),
    MEM_OFF_INFO_DEFINE(F39, pMEM_AC_BACK_DATA, nRTCTime),
    MEM_OFF_INFO_DEFINE(F40, pMEM_AC_BACK_DATA, sBcClk),
    
	{FEND, 1, 0, sizeof(pMEM_AC_BACK_DATA), 0}
};

//(FLASH备份)交互数据
const MEM_OFF_INFO g_sACBackFlhDataOff[] =
{
    //MEM_OFF_INFO_DEFINE(F1, pMEM_AC_BACK_FLH_DATA, nXBackBuff[0]),
    
    MEM_OFF_INFO_DEFINE(F1, pMEM_AC_BACK_FLH_DATA, sDayInfo),	
    MEM_OFF_INFO_DEFINE(F2, pMEM_AC_BACK_FLH_DATA, sRDayInfo),	
    MEM_OFF_INFO_DEFINE(F3, pMEM_AC_BACK_FLH_DATA, sSsdjInfo),	
    MEM_OFF_INFO_DEFINE(F4, pMEM_AC_BACK_FLH_DATA, sDsdjInfo),   
    MEM_OFF_INFO_DEFINE(F5, pMEM_AC_BACK_FLH_DATA, sSqdjInfo),   
    MEM_OFF_INFO_DEFINE(F6, pMEM_AC_BACK_FLH_DATA, sSddjInfo),   
    MEM_OFF_INFO_DEFINE(F7, pMEM_AC_BACK_FLH_DATA, sMONInfo),
    MEM_OFF_INFO_DEFINE(F8, pMEM_AC_BACK_FLH_DATA, sEvtAxsyInfo),	
    MEM_OFF_INFO_DEFINE(F9, pMEM_AC_BACK_FLH_DATA, sEvtBxsyInfo),	
    MEM_OFF_INFO_DEFINE(F10, pMEM_AC_BACK_FLH_DATA, sEvtCxsyInfo),	
    MEM_OFF_INFO_DEFINE(F11, pMEM_AC_BACK_FLH_DATA, sEvtAxdxInfo),	
    MEM_OFF_INFO_DEFINE(F12, pMEM_AC_BACK_FLH_DATA, sEvtBxdxInfo),	
    MEM_OFF_INFO_DEFINE(F13, pMEM_AC_BACK_FLH_DATA, sEvtCxdxInfo),	
    MEM_OFF_INFO_DEFINE(F14, pMEM_AC_BACK_FLH_DATA, sEvtQsyInfo), 	
    MEM_OFF_INFO_DEFINE(F15, pMEM_AC_BACK_FLH_DATA, sEvtDynxInfo),	
    MEM_OFF_INFO_DEFINE(F16, pMEM_AC_BACK_FLH_DATA, sEvtAxslInfo),	
    MEM_OFF_INFO_DEFINE(F17, pMEM_AC_BACK_FLH_DATA, sEvtBxslInfo),	
    MEM_OFF_INFO_DEFINE(F18, pMEM_AC_BACK_FLH_DATA, sEvtCxslInfo),	
    MEM_OFF_INFO_DEFINE(F19, pMEM_AC_BACK_FLH_DATA, sEvtDDInfo),      
    MEM_OFF_INFO_DEFINE(F20, pMEM_AC_BACK_FLH_DATA, sEvtXlqlInfo),	
    MEM_OFF_INFO_DEFINE(F21, pMEM_AC_BACK_FLH_DATA, sEvtDbqlInfo),	
    MEM_OFF_INFO_DEFINE(F22, pMEM_AC_BACK_FLH_DATA, sEvtSjqlInfo),	
    MEM_OFF_INFO_DEFINE(F23, pMEM_AC_BACK_FLH_DATA, sEvtBcInfo),      
    MEM_OFF_INFO_DEFINE(F24, pMEM_AC_BACK_FLH_DATA, sEvtJsInfo),  
    
    MEM_OFF_INFO_DEFINE(F25, pMEM_AC_BACK_FLH_DATA, nSyNUM),			
    MEM_OFF_INFO_DEFINE(F26, pMEM_AC_BACK_FLH_DATA, sSyFssk),		    
    MEM_OFF_INFO_DEFINE(F27, pMEM_AC_BACK_FLH_DATA, sSyJssk),		    
    MEM_OFF_INFO_DEFINE(F28, pMEM_AC_BACK_FLH_DATA, nAxsyNUM),		
    MEM_OFF_INFO_DEFINE(F29, pMEM_AC_BACK_FLH_DATA, nBxsyNUM),		
    MEM_OFF_INFO_DEFINE(F30, pMEM_AC_BACK_FLH_DATA, nCxsyNUM),		
    MEM_OFF_INFO_DEFINE(F31, pMEM_AC_BACK_FLH_DATA, nDxNUM),			
    MEM_OFF_INFO_DEFINE(F32, pMEM_AC_BACK_FLH_DATA, nAxdxNUM),		
    MEM_OFF_INFO_DEFINE(F33, pMEM_AC_BACK_FLH_DATA, nBxdxNUM),		
    MEM_OFF_INFO_DEFINE(F34, pMEM_AC_BACK_FLH_DATA, nCxdxNUM),		
    MEM_OFF_INFO_DEFINE(F35, pMEM_AC_BACK_FLH_DATA, nQsyNUM),		    
    MEM_OFF_INFO_DEFINE(F36, pMEM_AC_BACK_FLH_DATA, nDynxNum),		
    MEM_OFF_INFO_DEFINE(F37, pMEM_AC_BACK_FLH_DATA, nSlNUM),			
    MEM_OFF_INFO_DEFINE(F38, pMEM_AC_BACK_FLH_DATA, nAxslNUM),		
    MEM_OFF_INFO_DEFINE(F39, pMEM_AC_BACK_FLH_DATA, nBxslNUM),		
    MEM_OFF_INFO_DEFINE(F40, pMEM_AC_BACK_FLH_DATA, nCxslNUM),		
    MEM_OFF_INFO_DEFINE(F41, pMEM_AC_BACK_FLH_DATA, nDdNum),			
    MEM_OFF_INFO_DEFINE(F42, pMEM_AC_BACK_FLH_DATA, nXlqlNum),		
    MEM_OFF_INFO_DEFINE(F43, pMEM_AC_BACK_FLH_DATA, nDbqlNum),		
    MEM_OFF_INFO_DEFINE(F44, pMEM_AC_BACK_FLH_DATA, nSjqlNum),		
    MEM_OFF_INFO_DEFINE(F45, pMEM_AC_BACK_FLH_DATA, nBcNum),			
    MEM_OFF_INFO_DEFINE(F46, pMEM_AC_BACK_FLH_DATA, nJsNum),			
    MEM_OFF_INFO_DEFINE(F47, pMEM_AC_BACK_FLH_DATA, nBroadJsFlag),	
    MEM_OFF_INFO_DEFINE(F48, pMEM_AC_BACK_FLH_DATA, sRealData),		
    
    MEM_OFF_INFO_DEFINE(F49, pMEM_AC_BACK_FLH_DATA, nGyNUM),			
    MEM_OFF_INFO_DEFINE(F50, pMEM_AC_BACK_FLH_DATA, sGyFssk),		    
  	MEM_OFF_INFO_DEFINE(F51, pMEM_AC_BACK_FLH_DATA, sGyJssk),		    
  	MEM_OFF_INFO_DEFINE(F52, pMEM_AC_BACK_FLH_DATA, nAxgyNUM),		
  	MEM_OFF_INFO_DEFINE(F53, pMEM_AC_BACK_FLH_DATA, nBxgyNUM),		
    MEM_OFF_INFO_DEFINE(F54, pMEM_AC_BACK_FLH_DATA, nCxgyNUM),    
    MEM_OFF_INFO_DEFINE(F55, pMEM_AC_BACK_FLH_DATA, sEvtAxgyInfo),		
  	MEM_OFF_INFO_DEFINE(F56, pMEM_AC_BACK_FLH_DATA, sEvtBxgyInfo),		
    MEM_OFF_INFO_DEFINE(F57, pMEM_AC_BACK_FLH_DATA, sEvtCxgyInfo),
    
    MEM_OFF_INFO_DEFINE(F58, pMEM_AC_BACK_FLH_DATA, nGlNUM),			
    MEM_OFF_INFO_DEFINE(F59, pMEM_AC_BACK_FLH_DATA, sGlFssk),		    
  	MEM_OFF_INFO_DEFINE(F60, pMEM_AC_BACK_FLH_DATA, sGlJssk),		    
  	MEM_OFF_INFO_DEFINE(F61, pMEM_AC_BACK_FLH_DATA, nAxglNUM),		
  	MEM_OFF_INFO_DEFINE(F62, pMEM_AC_BACK_FLH_DATA, nBxglNUM),		
    MEM_OFF_INFO_DEFINE(F63, pMEM_AC_BACK_FLH_DATA, nCxglNUM),    
    MEM_OFF_INFO_DEFINE(F64, pMEM_AC_BACK_FLH_DATA, sEvtAxglInfo),		
  	MEM_OFF_INFO_DEFINE(F65, pMEM_AC_BACK_FLH_DATA, sEvtBxglInfo),		
    MEM_OFF_INFO_DEFINE(F66, pMEM_AC_BACK_FLH_DATA, sEvtCxglInfo),
    
    MEM_OFF_INFO_DEFINE(F67, pMEM_AC_BACK_FLH_DATA, nClNUM),			
    MEM_OFF_INFO_DEFINE(F68, pMEM_AC_BACK_FLH_DATA, sClFssk),		    
  	MEM_OFF_INFO_DEFINE(F69, pMEM_AC_BACK_FLH_DATA, sClJssk),		    
  	MEM_OFF_INFO_DEFINE(F70, pMEM_AC_BACK_FLH_DATA, nAxclNUM),		
  	MEM_OFF_INFO_DEFINE(F71, pMEM_AC_BACK_FLH_DATA, nBxclNUM),		
    MEM_OFF_INFO_DEFINE(F72, pMEM_AC_BACK_FLH_DATA, nCxclNUM),    
    MEM_OFF_INFO_DEFINE(F73, pMEM_AC_BACK_FLH_DATA, sEvtAxclInfo),		
  	MEM_OFF_INFO_DEFINE(F74, pMEM_AC_BACK_FLH_DATA, sEvtBxclInfo),		
    MEM_OFF_INFO_DEFINE(F75, pMEM_AC_BACK_FLH_DATA, sEvtCxclInfo),
    
    MEM_OFF_INFO_DEFINE(F76, pMEM_AC_BACK_FLH_DATA, nGzNUM),			
    MEM_OFF_INFO_DEFINE(F77, pMEM_AC_BACK_FLH_DATA, sGzFssk),		    
  	MEM_OFF_INFO_DEFINE(F78, pMEM_AC_BACK_FLH_DATA, sGzJssk),		    
  	MEM_OFF_INFO_DEFINE(F79, pMEM_AC_BACK_FLH_DATA, nAxgzNUM),		
  	MEM_OFF_INFO_DEFINE(F80, pMEM_AC_BACK_FLH_DATA, nBxgzNUM),		
    MEM_OFF_INFO_DEFINE(F81, pMEM_AC_BACK_FLH_DATA, nCxgzNUM),    
    MEM_OFF_INFO_DEFINE(F82, pMEM_AC_BACK_FLH_DATA, sEvtAxgzInfo),		
  	MEM_OFF_INFO_DEFINE(F83, pMEM_AC_BACK_FLH_DATA, sEvtBxgzInfo),		
    MEM_OFF_INFO_DEFINE(F84, pMEM_AC_BACK_FLH_DATA, sEvtCxgzInfo),
    
    MEM_OFF_INFO_DEFINE(F85, pMEM_AC_BACK_FLH_DATA, nACEvtTrip),
    
    MEM_OFF_INFO_DEFINE(F86, pMEM_AC_BACK_FLH_DATA, nOpenCoverNum),
    MEM_OFF_INFO_DEFINE(F87, pMEM_AC_BACK_FLH_DATA, sOpenCoverInfo),
    
    MEM_OFF_INFO_DEFINE(F88, pMEM_AC_BACK_FLH_DATA, nACEvtTripNum),//跳闸
    MEM_OFF_INFO_DEFINE(F89, pMEM_AC_BACK_FLH_DATA, sACEvtTripInfo),
    
    MEM_OFF_INFO_DEFINE(F90, pMEM_AC_BACK_FLH_DATA, nEvtSwitchOnNum),//合闸
    MEM_OFF_INFO_DEFINE(F91, pMEM_AC_BACK_FLH_DATA, sEvtSwitchOnInfo),
    
    MEM_OFF_INFO_DEFINE(F92, pMEM_AC_BACK_FLH_DATA, nEvtSecretKeyNum),//密钥
    MEM_OFF_INFO_DEFINE(F93, pMEM_AC_BACK_FLH_DATA, sEvtSecretKeyInfo),
    
    MEM_OFF_INFO_DEFINE(F94, pMEM_AC_BACK_FLH_DATA, nEvtLoadSwitchNum),//负荷开关
    MEM_OFF_INFO_DEFINE(F95, pMEM_AC_BACK_FLH_DATA, sEvtLoadSwitchInfo),
    
    MEM_OFF_INFO_DEFINE(F96, pMEM_AC_BACK_FLH_DATA, nEvtPowerAbnlNum),//电源异常
    MEM_OFF_INFO_DEFINE(F97, pMEM_AC_BACK_FLH_DATA, sEvtPowerAbnlInfo),
    
    MEM_OFF_INFO_DEFINE(F98, pMEM_AC_BACK_FLH_DATA, nEvtClockTrbNum),//时钟故障异常
    MEM_OFF_INFO_DEFINE(F99, pMEM_AC_BACK_FLH_DATA, sEvtClockTrbInfo),
    
    MEM_OFF_INFO_DEFINE(F100, pMEM_AC_BACK_FLH_DATA, nEvtChipTrbNum),//计量芯片故障异常
    MEM_OFF_INFO_DEFINE(F101, pMEM_AC_BACK_FLH_DATA, sEvtChipTrbInfo),
    
    MEM_OFF_INFO_DEFINE(F102, pMEM_AC_BACK_FLH_DATA, nQyNUM),			
    MEM_OFF_INFO_DEFINE(F103, pMEM_AC_BACK_FLH_DATA, sQyFssk),		    
    MEM_OFF_INFO_DEFINE(F104, pMEM_AC_BACK_FLH_DATA, sQyJssk),
    MEM_OFF_INFO_DEFINE(F105, pMEM_AC_BACK_FLH_DATA, nAxqyNUM),		
    MEM_OFF_INFO_DEFINE(F106, pMEM_AC_BACK_FLH_DATA, nBxqyNUM),		
    MEM_OFF_INFO_DEFINE(F107, pMEM_AC_BACK_FLH_DATA, nCxqyNUM),	
    
    MEM_OFF_INFO_DEFINE(F108, pMEM_AC_BACK_FLH_DATA, nDlNUM),
    MEM_OFF_INFO_DEFINE(F109, pMEM_AC_BACK_FLH_DATA, nAxdlNUM),		
    MEM_OFF_INFO_DEFINE(F110, pMEM_AC_BACK_FLH_DATA, nBxdlNUM),		
    MEM_OFF_INFO_DEFINE(F111, pMEM_AC_BACK_FLH_DATA, nCxdlNUM),
    MEM_OFF_INFO_DEFINE(F112, pMEM_AC_BACK_FLH_DATA, nACOffset),
    MEM_OFF_INFO_DEFINE(F113, pMEM_AC_BACK_FLH_DATA, sSetParametersInfo),  //设置界面参数
    

    {FEND, 1, 0, sizeof(MEM_AC_BACK_FLH_DATA), 0}
};



















